// Writes src/assets/tokens.css from design/tokens.cjs. Run with `npm run tokens`.
const { writeFileSync } = require("node:fs");
const { join } = require("node:path");
const { light, dark, ramps } = require("../design/tokens.cjs");

function rgb(hex) {
  const h = hex.replace("#", "");
  const n = parseInt(h.length === 3 ? h.split("").map((c) => c + c).join("") : h, 16);
  return `${(n >> 16) & 255} ${(n >> 8) & 255} ${n & 255}`;
}

function block(theme) {
  const lines = [];
  for (const [name, steps] of Object.entries(ramps)) {
    const values = theme[name];
    if (values.length !== steps.length) throw new Error(`${name}: ${values.length} values for ${steps.length} steps`);
    steps.forEach((step, i) => lines.push(`  --c-${name}-${step}: ${rgb(values[i])};`));
  }
  for (const [name, value] of Object.entries(theme.single)) {
    lines.push(`  --c-${name}: ${name.endsWith("-rgb") ? value : rgb(value)};`);
  }
  return lines.join("\n");
}

const css = `/* Generated by scripts/gen-tokens.cjs from design/tokens.cjs. Do not edit. */
:root {
  color-scheme: light dark;
${block(light)}
}

@media (prefers-color-scheme: dark) {
  :root {
${block(dark)}
  }
}
`;

const out = join(__dirname, "..", "src", "assets", "tokens.css");
writeFileSync(out, css);
console.log(`wrote ${out}`);
