// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ask} from '../models';

export function DeleteKey(arg1:string):Promise<void>;

export function SaveProvider(arg1:string,arg2:ask.ProviderInput):Promise<void>;

export function SetEnabled(arg1:boolean):Promise<void>;

export function SetKey(arg1:string,arg2:string):Promise<void>;

export function Status():Promise<ask.Status>;

export function Test(arg1:string):Promise<ask.TestResult>;
