// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteKey(arg1) {
  return window['go']['app']['AIService']['DeleteKey'](arg1);
}

export function SaveProvider(arg1, arg2) {
  return window['go']['app']['AIService']['SaveProvider'](arg1, arg2);
}

export function SetEnabled(arg1) {
  return window['go']['app']['AIService']['SetEnabled'](arg1);
}

export function SetKey(arg1, arg2) {
  return window['go']['app']['AIService']['SetKey'](arg1, arg2);
}

export function Status() {
  return window['go']['app']['AIService']['Status']();
}

export function Test(arg1) {
  return window['go']['app']['AIService']['Test'](arg1);
}
