// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function QueueSnapshots(arg1, arg2) {
  return window['go']['app']['AppService']['QueueSnapshots'](arg1, arg2);
}

export function TakePendingSnapshots() {
  return window['go']['app']['AppService']['TakePendingSnapshots']();
}

export function Version() {
  return window['go']['app']['AppService']['Version']();
}
