// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function QueueSnapshots(arg1:Array<string>,arg2:string):Promise<boolean>;

export function TakePendingSnapshots():Promise<Array<string>>;

export function Version():Promise<string>;
