// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ask} from '../models';

export function Cancel(arg1:string):Promise<void>;

export function Chat(arg1:string,arg2:string):Promise<string>;

export function Embed(arg1:string,arg2:Array<string>):Promise<Array<any>>;

export function Models():Promise<Array<ask.Model>>;
