// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['app']['AskService']['Cancel'](arg1);
}

export function Chat(arg1, arg2) {
  return window['go']['app']['AskService']['Chat'](arg1, arg2);
}

export function Embed(arg1, arg2) {
  return window['go']['app']['AskService']['Embed'](arg1, arg2);
}

export function Models() {
  return window['go']['app']['AskService']['Models']();
}
