// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Compare(arg1, arg2) {
  return window['go']['app']['ChangesService']['Compare'](arg1, arg2);
}

export function ComputeReadings(arg1) {
  return window['go']['app']['ChangesService']['ComputeReadings'](arg1);
}

export function ForgetScan(arg1) {
  return window['go']['app']['ChangesService']['ForgetScan'](arg1);
}

export function Readings(arg1) {
  return window['go']['app']['ChangesService']['Readings'](arg1);
}
