// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {changes} from '../models';
import {app} from '../models';

export function Compare(arg1:string,arg2:string):Promise<changes.ChangeSet>;

export function ComputeReadings(arg1:string):Promise<void>;

export function ForgetScan(arg1:string):Promise<void>;

export function Readings(arg1:string):Promise<Array<app.TrendPoint>>;
