// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {clone} from '../models';

export function Cancel(arg1:string):Promise<void>;

export function ChooseParent(arg1:string):Promise<string>;

export function Forget(arg1:string):Promise<void>;

export function Jobs():Promise<Array<clone.Job>>;

export function Plan(arg1:string,arg2:string):Promise<clone.Plan>;

export function Start(arg1:clone.Request):Promise<clone.Job>;
