// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['app']['CloneService']['Cancel'](arg1);
}

export function ChooseParent(arg1) {
  return window['go']['app']['CloneService']['ChooseParent'](arg1);
}

export function Forget(arg1) {
  return window['go']['app']['CloneService']['Forget'](arg1);
}

export function Jobs() {
  return window['go']['app']['CloneService']['Jobs']();
}

export function Plan(arg1, arg2) {
  return window['go']['app']['CloneService']['Plan'](arg1, arg2);
}

export function Start(arg1) {
  return window['go']['app']['CloneService']['Start'](arg1);
}
