// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {report} from '../models';

export function Delete(arg1:string):Promise<void>;

export function DeleteReport(arg1:string):Promise<void>;

export function Figure(arg1:string):Promise<string>;

export function List(arg1:string):Promise<Array<store.Pin>>;

export function OpenPDF(arg1:string,arg2:string):Promise<void>;

export function RenderPDF(arg1:report.Doc):Promise<string>;

export function Reorder(arg1:string,arg2:Array<string>):Promise<void>;

export function ReorderReports(arg1:string,arg2:Array<string>):Promise<void>;

export function Reports(arg1:string):Promise<Array<store.Report>>;

export function SaveFigure(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveReport(arg1:store.Report):Promise<store.Report>;

export function Upsert(arg1:store.Pin):Promise<store.Pin>;
