// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function Delete(arg1:string):Promise<void>;

export function Figure(arg1:string):Promise<string>;

export function List(arg1:string):Promise<Array<store.Pin>>;

export function Reorder(arg1:string,arg2:Array<string>):Promise<void>;

export function SaveFigure(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Upsert(arg1:store.Pin):Promise<store.Pin>;
