// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CopyText(arg1:string):Promise<void>;

export function OpenFile(arg1:string,arg2:Array<app.FileFilter>):Promise<string>;

export function Reveal(arg1:string):Promise<void>;

export function SaveBundle(arg1:string,arg2:Array<app.BundleFile>):Promise<string>;

export function SaveFile(arg1:app.SaveRequest):Promise<string>;
