// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyText(arg1) {
  return window['go']['app']['FilesService']['CopyText'](arg1);
}

export function OpenFile(arg1, arg2) {
  return window['go']['app']['FilesService']['OpenFile'](arg1, arg2);
}

export function Reveal(arg1) {
  return window['go']['app']['FilesService']['Reveal'](arg1);
}

export function SaveBundle(arg1, arg2) {
  return window['go']['app']['FilesService']['SaveBundle'](arg1, arg2);
}

export function SaveFile(arg1) {
  return window['go']['app']['FilesService']['SaveFile'](arg1);
}
