// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function Delete(arg1:string):Promise<void>;

export function List(arg1:string):Promise<Array<store.Note>>;

export function Save(arg1:store.Note):Promise<store.Note>;
