// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['app']['NotesService']['Delete'](arg1);
}

export function List(arg1) {
  return window['go']['app']['NotesService']['List'](arg1);
}

export function Save(arg1) {
  return window['go']['app']['NotesService']['Save'](arg1);
}
