// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalysisRevision() {
  return window['go']['app']['QueryService']['AnalysisRevision']();
}

export function Console(arg1, arg2) {
  return window['go']['app']['QueryService']['Console'](arg1, arg2);
}

export function CurrentScan() {
  return window['go']['app']['QueryService']['CurrentScan']();
}

export function FindInCode(arg1, arg2, arg3) {
  return window['go']['app']['QueryService']['FindInCode'](arg1, arg2, arg3);
}

export function FindLines(arg1, arg2, arg3, arg4) {
  return window['go']['app']['QueryService']['FindLines'](arg1, arg2, arg3, arg4);
}

export function Open(arg1) {
  return window['go']['app']['QueryService']['Open'](arg1);
}

export function Query(arg1) {
  return window['go']['app']['QueryService']['Query'](arg1);
}

export function QueryIn(arg1, arg2) {
  return window['go']['app']['QueryService']['QueryIn'](arg1, arg2);
}

export function QueryLimited(arg1, arg2, arg3, arg4) {
  return window['go']['app']['QueryService']['QueryLimited'](arg1, arg2, arg3, arg4);
}
