// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentScan() {
  return window['go']['app']['QueryService']['CurrentScan']();
}

export function Open(arg1) {
  return window['go']['app']['QueryService']['Open'](arg1);
}

export function Query(arg1) {
  return window['go']['app']['QueryService']['Query'](arg1);
}
