// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {query} from '../models';

export function AnalysisRevision():Promise<number>;

export function Console(arg1:string,arg2:string):Promise<query.Limited>;

export function CurrentScan():Promise<string>;

export function Open(arg1:string):Promise<void>;

export function Query(arg1:string):Promise<Array<Record<string, any>>>;

export function QueryIn(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function QueryLimited(arg1:string,arg2:string,arg3:number,arg4:number):Promise<query.Limited>;
