// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function IsRunning(arg1:string):Promise<boolean>;

export function Start(arg1:string):Promise<store.Scan>;
