// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsRunning(arg1) {
  return window['go']['app']['ScanService']['IsRunning'](arg1);
}

export function Start(arg1) {
  return window['go']['app']['ScanService']['Start'](arg1);
}
