// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Put(arg1, arg2, arg3) {
  return window['go']['app']['StateService']['Put'](arg1, arg2, arg3);
}

export function PutMany(arg1, arg2) {
  return window['go']['app']['StateService']['PutMany'](arg1, arg2);
}

export function PutSetting(arg1, arg2) {
  return window['go']['app']['StateService']['PutSetting'](arg1, arg2);
}

export function Settings() {
  return window['go']['app']['StateService']['Settings']();
}

export function Workspace(arg1) {
  return window['go']['app']['StateService']['Workspace'](arg1);
}
