// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Put(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PutMany(arg1:string,arg2:Record<string, string>):Promise<void>;

export function PutSetting(arg1:string,arg2:string):Promise<void>;

export function Settings():Promise<Record<string, string>>;

export function Workspace(arg1:string):Promise<Record<string, string>>;
