// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function Create(arg1:string,arg2:string):Promise<store.Workspace>;

export function Delete(arg1:string):Promise<void>;

export function DeleteScan(arg1:string):Promise<void>;

export function Get(arg1:string):Promise<store.Workspace>;

export function List():Promise<Array<store.Workspace>>;

export function ListScans(arg1:string):Promise<Array<store.Scan>>;
