// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2) {
  return window['go']['app']['WorkspaceService']['Create'](arg1, arg2);
}

export function Delete(arg1) {
  return window['go']['app']['WorkspaceService']['Delete'](arg1);
}

export function DeleteScan(arg1) {
  return window['go']['app']['WorkspaceService']['DeleteScan'](arg1);
}

export function DeleteScans(arg1) {
  return window['go']['app']['WorkspaceService']['DeleteScans'](arg1);
}

export function Get(arg1) {
  return window['go']['app']['WorkspaceService']['Get'](arg1);
}

export function HeadDrift(arg1, arg2) {
  return window['go']['app']['WorkspaceService']['HeadDrift'](arg1, arg2);
}

export function ImportSnapshot(arg1, arg2) {
  return window['go']['app']['WorkspaceService']['ImportSnapshot'](arg1, arg2);
}

export function InspectSnapshot(arg1) {
  return window['go']['app']['WorkspaceService']['InspectSnapshot'](arg1);
}

export function LabelScan(arg1, arg2) {
  return window['go']['app']['WorkspaceService']['LabelScan'](arg1, arg2);
}

export function List() {
  return window['go']['app']['WorkspaceService']['List']();
}

export function ListScans(arg1) {
  return window['go']['app']['WorkspaceService']['ListScans'](arg1);
}

export function OpenInEditor(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['WorkspaceService']['OpenInEditor'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function PickSnapshot() {
  return window['go']['app']['WorkspaceService']['PickSnapshot']();
}

export function PreviewIgnore(arg1, arg2) {
  return window['go']['app']['WorkspaceService']['PreviewIgnore'](arg1, arg2);
}

export function Rename(arg1, arg2) {
  return window['go']['app']['WorkspaceService']['Rename'](arg1, arg2);
}

export function RevealSnapshot(arg1) {
  return window['go']['app']['WorkspaceService']['RevealSnapshot'](arg1);
}

export function RevealWorkspaceFile(arg1, arg2) {
  return window['go']['app']['WorkspaceService']['RevealWorkspaceFile'](arg1, arg2);
}

export function SaveSnapshotCopy(arg1, arg2) {
  return window['go']['app']['WorkspaceService']['SaveSnapshotCopy'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['app']['WorkspaceService']['SelectFolder']();
}

export function SetBaseline(arg1, arg2) {
  return window['go']['app']['WorkspaceService']['SetBaseline'](arg1, arg2);
}

export function SnapshotPath(arg1) {
  return window['go']['app']['WorkspaceService']['SnapshotPath'](arg1);
}

export function StorageSummary() {
  return window['go']['app']['WorkspaceService']['StorageSummary']();
}
