// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2) {
  return window['go']['app']['WorkspaceService']['Create'](arg1, arg2);
}

export function Delete(arg1) {
  return window['go']['app']['WorkspaceService']['Delete'](arg1);
}

export function DeleteScan(arg1) {
  return window['go']['app']['WorkspaceService']['DeleteScan'](arg1);
}

export function Get(arg1) {
  return window['go']['app']['WorkspaceService']['Get'](arg1);
}

export function List() {
  return window['go']['app']['WorkspaceService']['List']();
}

export function ListScans(arg1) {
  return window['go']['app']['WorkspaceService']['ListScans'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['app']['WorkspaceService']['Rename'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['app']['WorkspaceService']['SelectFolder']();
}
