// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {app} from '../models';

export function Create(arg1:string,arg2:string):Promise<store.Workspace>;

export function Delete(arg1:string):Promise<void>;

export function DeleteScan(arg1:string):Promise<void>;

export function Get(arg1:string):Promise<store.Workspace>;

export function LabelScan(arg1:string,arg2:string):Promise<void>;

export function List():Promise<Array<store.Workspace>>;

export function ListScans(arg1:string):Promise<Array<store.Scan>>;

export function Rename(arg1:string,arg2:string):Promise<store.Workspace>;

export function SelectFolder():Promise<app.FolderPick>;

export function SetBaseline(arg1:string,arg2:string):Promise<void>;
