// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {app} from '../models';

export function Create(arg1:string,arg2:string):Promise<store.Workspace>;

export function Delete(arg1:string):Promise<void>;

export function DeleteScan(arg1:string):Promise<void>;

export function Get(arg1:string):Promise<store.Workspace>;

export function HeadDrift(arg1:string,arg2:string):Promise<app.HeadDrift>;

export function LabelScan(arg1:string,arg2:string):Promise<void>;

export function List():Promise<Array<store.Workspace>>;

export function ListScans(arg1:string):Promise<Array<store.Scan>>;

export function OpenInEditor(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:string):Promise<app.EditorOpened>;

export function Rename(arg1:string,arg2:string):Promise<store.Workspace>;

export function RevealSnapshot(arg1:string):Promise<void>;

export function RevealWorkspaceFile(arg1:string,arg2:string):Promise<void>;

export function SaveSnapshotCopy(arg1:string,arg2:boolean):Promise<string>;

export function SelectFolder():Promise<app.FolderPick>;

export function SetBaseline(arg1:string,arg2:string):Promise<void>;

export function SnapshotPath(arg1:string):Promise<string>;
