// Folder X-ray: what a grab-bag folder actually holds.
//
// A folder called utils or helpers or common says nothing about its files.
// The X-ray reads each file the way a person would on first contact (what it
// says about itself, what it exports, who uses it and from where, what it
// uses, what it changes with) and then groups the files into topics by those
// same signals. It is the manual pass of a restructure, done by the tool.

import { louvain, type WeightedEdge } from "~/features/lens-builder/louvain"
import { CODE_EXTENSIONS, extensionOf } from "~/features/snapshot/coverage"
import { isTestPath } from "~/features/snapshot/fileRole"

export interface XrayFile {
    path: string
    lines: number
    role: string
    commits: number
    health: number | null
    /** The first thing the file says about itself, one sentence. */
    summary: string
    exports: string[]
    /** Production files that import this one. */
    usedBy: string[]
    /** Test files that import this one. */
    testedBy: string[]
    /** Files this one imports. */
    uses: string[]
    /** Files changed in the same commits, with how many. */
    changesWith: Array<{ file: string; shared: number }>
}

// ── Reading a file's own description ─────────────────────────────────────

const LICENSE = /copyright|license|licence|spdx|all rights reserved|generated by|do not edit|eslint-disable|@ts-|prettier-ignore/i

/**
 * The first comment in a file that reads like a description: at least a few
 * words, not a licence header, not a tool directive. Returns its first
 * sentence, or "" when the file says nothing about itself.
 */
export function firstComment(content: string, maxLen = 200): string {
    const lines = content.split(/\r?\n/).slice(0, 120)
    const blocks: string[] = []
    let i = 0
    while (i < lines.length && blocks.length < 6) {
        const t = lines[i].trim()
        if (t.startsWith("//") || (t.startsWith("#") && !t.startsWith("#!") && !t.startsWith("#include") && !t.startsWith("#region"))) {
            const marker = t.startsWith("//") ? "//" : "#"
            const buf: string[] = []
            while (i < lines.length && lines[i].trim().startsWith(marker)) { buf.push(lines[i].trim().replace(/^(\/\/+|#+)\s?/, "")); i++ }
            blocks.push(buf.join(" "))
            continue
        }
        const open = t.match(/^(\/\*\*?|<!--|"""|''')/)
        if (open) {
            const close = open[1] === "<!--" ? "-->" : open[1].startsWith("/*") ? "*/" : open[1]
            const buf: string[] = []
            let first = t.slice(open[1].length)
            let j = i
            let line = first
            for (;;) {
                const end = line.indexOf(close)
                if (end >= 0) { buf.push(line.slice(0, end)); break }
                buf.push(line)
                j++
                if (j >= lines.length) break
                line = lines[j].trim()
                if (!line.startsWith(close)) line = line.replace(/^\*\s?/, "")
            }
            blocks.push(buf.join(" "))
            i = j + 1
            continue
        }
        i++
    }
    for (const b of blocks) {
        const text = b.replace(/\s+/g, " ").replace(/^[-*=\s]+/, "").trim()
        if (text.split(" ").length < 4 || LICENSE.test(text)) continue
        const sentence = text.match(/^(.+?[.!?])(\s|$)/)?.[1] ?? text
        return sentence.length > maxLen ? `${sentence.slice(0, maxLen - 1)}…` : sentence
    }
    return ""
}

// ── Where a neighbour sits ────────────────────────────────────────────────

/**
 * The part of the codebase a file sits in, seen from `dir`: its directory,
 * cut to two levels below `dir`'s parent, written relative to that parent.
 * From frontend/src/utils, frontend/src/components/report/X.vue sits in
 * "components/report" and frontend/src/utils/x.ts in "utils".
 */
export function areaOf(file: string, dir: string): string {
    const parent = dir.includes("/") ? dir.slice(0, dir.lastIndexOf("/")) : ""
    const base = file.includes("/") ? file.slice(0, file.lastIndexOf("/")) : "."
    const rel = parent && base.startsWith(parent + "/") ? base.slice(parent.length + 1) : base
    return rel.split("/").slice(0, 2).join("/") || "."
}

/** "components/report ×5, pages ×2": neighbours rolled up by area, busiest first. */
export function byArea(files: Iterable<string>, dir: string): Array<{ area: string; files: string[] }> {
    const m = new Map<string, string[]>()
    for (const f of files) {
        const a = areaOf(f, dir)
        m.set(a, [...(m.get(a) ?? []), f])
    }
    return [...m].map(([area, fs]) => ({ area, files: fs.sort() })).sort((x, y) => y.files.length - x.files.length || x.area.localeCompare(y.area))
}

// ── Topics ────────────────────────────────────────────────────────────────

const GENERIC = new Set(["use", "get", "set", "is", "to", "of", "the", "a", "an", "and", "for", "in", "on", "ts", "js", "tsx", "jsx", "vue", "py", "go", "java", "php", "cs", "kt", "test", "tests", "spec", "index", "util", "utils", "helper", "helpers", "common", "shared", "lib", "impl", "model", "models", "store", "stores", "service", "services", "type", "types"])

/** The words a file is named with: `useDimensionStudio.ts` → dimension, studio. */
export function nameTokens(path: string): string[] {
    const base = path.slice(path.lastIndexOf("/") + 1).replace(/\.[^.]+$/, "").replace(/\.(test|spec|bench|parity)$/i, "")
    return base
        .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
        .replace(/([A-Z])([A-Z][a-z])/g, "$1 $2")
        .split(/[\s_\-.]+/)
        .map(t => t.toLowerCase())
        .filter(t => t.length > 1 && !GENERIC.has(t))
}

export interface Topic {
    /** Named by the word its members share most, or by its biggest file. */
    name: string
    files: string[]
    lines: number
    /** Share of the members' tie weight that stays inside the topic, 0..1. */
    cohesion: number
}

const jaccard = (a: ReadonlySet<string>, b: ReadonlySet<string>) => {
    if (!a.size || !b.size) return 0
    let n = 0
    for (const x of a) if (b.has(x)) n++
    return n / (a.size + b.size - n)
}

/**
 * Weighted Jaccard: a neighbour shared by two files counts by how selective it
 * is. A page that imports two files says they belong together; a composable
 * that imports twenty of the folder's files says almost nothing about any two.
 */
const weightedJaccard = (a: ReadonlySet<string>, b: ReadonlySet<string>, weightOf: (x: string) => number) => {
    if (!a.size || !b.size) return 0
    let inter = 0, union = 0
    for (const x of a) { const w = weightOf(x); union += w; if (b.has(x)) inter += w }
    for (const x of b) if (!a.has(x)) union += weightOf(x)
    return union ? inter / union : 0
}

/**
 * Groups a folder's production files by what ties them: importing each
 * other, being used by the same files, using the same files, changing
 * together, and sharing a word in their names. Tests follow the file they
 * test. Deterministic for the same input.
 */
export function topics(files: XrayFile[], resolution = 1): Topic[] {
    const isTest = (f: XrayFile) => f.role === "test" || /\.(test|spec)\.[a-z]+$/i.test(f.path)
    const prod = files.filter(f => !isTest(f))
    const ids = prod.map(f => f.path)
    const inDir = new Set(ids)
    const byPath = new Map(files.map(f => [f.path, f]))
    const usedBy = new Map(prod.map(f => [f.path, new Set(f.usedBy)]))
    const uses = new Map(prod.map(f => [f.path, new Set(f.uses)]))
    const tokens = new Map(prod.map(f => [f.path, new Set(nameTokens(f.path))]))
    const weight = new Map<string, number>()
    const add = (a: string, b: string, w: number) => {
        if (a === b || !(w > 0)) return
        const k = a < b ? `${a}\u0000${b}` : `${b}\u0000${a}`
        weight.set(k, (weight.get(k) ?? 0) + w)
    }
    for (const f of prod) {
        for (const u of f.uses) if (inDir.has(u)) add(f.path, u, 1)
        for (const c of f.changesWith) if (inDir.has(c.file)) add(f.path, c.file, Math.min(1, c.shared / Math.max(1, Math.min(f.commits || 1, byPath.get(c.file)?.commits || 1))))
    }
    // How many of the folder's files each neighbour touches: the fewer, the more it says.
    const reach = (sets: Map<string, Set<string>>) => {
        const n = new Map<string, number>()
        for (const set of sets.values()) for (const x of set) n.set(x, (n.get(x) ?? 0) + 1)
        return (x: string) => 1 / Math.max(1, n.get(x) ?? 1)
    }
    const importerWeight = reach(usedBy)
    const importedWeight = reach(uses)
    for (let i = 0; i < ids.length; i++) {
        for (let j = i + 1; j < ids.length; j++) {
            const a = ids[i], b = ids[j]
            add(a, b, weightedJaccard(usedBy.get(a)!, usedBy.get(b)!, importerWeight))
            add(a, b, 0.5 * weightedJaccard(uses.get(a)!, uses.get(b)!, importedWeight))
            add(a, b, 0.6 * jaccard(tokens.get(a)!, tokens.get(b)!))
        }
    }
    const edges: WeightedEdge[] = [...weight].map(([k, w]) => { const [a, b] = k.split("\u0000"); return { a, b, w } })
    const community = louvain(ids, edges, resolution)
    const members = new Map<number, string[]>()
    for (const id of ids) {
        const c = community.get(id)!
        members.set(c, [...(members.get(c) ?? []), id])
    }
    // Tests join the topic of the file they are named after.
    const home = new Map<string, number>()
    for (const [c, fs] of members) for (const f of fs) home.set(f.replace(/\.[^.]+$/, ""), c)
    for (const f of files) {
        if (!isTest(f)) continue
        const subject = f.path.replace(/\.(test|spec|bench\.test|parity\.test)\.[a-z]+$/i, "")
        const c = home.get(subject)
        if (c !== undefined) members.get(c)!.push(f.path)
    }
    const total = new Map<string, number>()
    for (const e of edges) { total.set(e.a, (total.get(e.a) ?? 0) + e.w); total.set(e.b, (total.get(e.b) ?? 0) + e.w) }
    const out: Topic[] = []
    for (const [, fs] of members) {
        const set = new Set(fs)
        let inside = 0, all = 0
        for (const e of edges) {
            const ia = set.has(e.a), ib = set.has(e.b)
            if (ia || ib) all += e.w
            if (ia && ib) inside += e.w
        }
        const count = new Map<string, number>()
        for (const f of fs) for (const t of tokens.get(f) ?? []) count.set(t, (count.get(t) ?? 0) + 1)
        const top = [...count].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))[0]
        const lines = fs.reduce((n, f) => n + (byPath.get(f)?.lines ?? 0), 0)
        const biggest = [...fs].sort((a, b) => (byPath.get(b)?.lines ?? 0) - (byPath.get(a)?.lines ?? 0))[0]
        const name = top && top[1] > 1 ? top[0] : (nameTokens(biggest)[0] ?? biggest.slice(biggest.lastIndexOf("/") + 1))
        out.push({ name, files: fs.sort(), lines, cohesion: all ? inside / all : 0 })
    }
    // Loners (nothing ties them to the rest) are one "Unclustered" topic, last.
    const alone = out.filter(t => t.files.filter(f => !isTest(byPath.get(f)!)).length === 1 && t.cohesion === 0)
    const grouped = out.filter(t => !alone.includes(t)).sort((a, b) => b.lines - a.lines || a.name.localeCompare(b.name))
    if (alone.length) grouped.push({ name: "Unclustered", files: alone.flatMap(t => t.files).sort(), lines: alone.reduce((n, t) => n + t.lines, 0), cohesion: 0 })
    return grouped
}

// ── Loading ───────────────────────────────────────────────────────────────

type Query = (sql: string) => Promise<any[]>

const lit = (s: string) => `'${s.replace(/'/g, "''")}'`
const likePrefix = (dir: string) => `${lit(dir.replace(/[\\%_]/g, c => `\\${c}`) + "/%")} ESCAPE '\\'`

/**
 * Everything the X-ray shows for `dir`, including its subfolders. `has`
 * says which tables exist. Co-change leaves out sweeping commits (more than
 * `sweep` files), the same way the engine's own co-change does.
 */
export async function loadXray(q: Query, dir: string, has: (table: string, column?: string) => boolean, sweep = 50): Promise<XrayFile[]> {
    const inDir = `name LIKE ${likePrefix(dir)}`
    const roleCol = has("files", "role") ? "role" : "'production' AS role"
    const healthCol = has("files", "codesmells__code_health") ? "codesmells__code_health AS health" : "NULL AS health"
    const commitsCol = has("files", "git__commits__total") ? "coalesce(git__commits__total, 0) AS commits" : "0 AS commits"
    const [rows, contents, units, edges, co] = await Promise.all([
        q(`SELECT name, coalesce(complexity__lines, 0) AS lines, ${roleCol}, ${commitsCol}, ${healthCol} FROM files WHERE ${inDir}`),
        has("file_contents") ? q(`SELECT file, substr(content, 1, 6000) AS head FROM file_contents WHERE file LIKE ${likePrefix(dir)}`) : Promise.resolve([]),
        has("units") ? q(`SELECT file, name FROM units WHERE file LIKE ${likePrefix(dir)} AND (owner IS NULL OR owner = '') ORDER BY name`) : Promise.resolve([]),
        has("unit_connections") ? q(`SELECT DISTINCT from_file AS a, to_file AS b FROM unit_connections WHERE from_file <> to_file AND (from_file LIKE ${likePrefix(dir)} OR to_file LIKE ${likePrefix(dir)})`) : Promise.resolve([]),
        has("git_commits") ? q(`WITH mine AS (SELECT DISTINCT file, commit_hash FROM git_commits WHERE file LIKE ${likePrefix(dir)}),
            sizes AS (SELECT commit_hash, count(DISTINCT file) AS n FROM git_commits WHERE commit_hash IN (SELECT commit_hash FROM mine) GROUP BY 1)
            SELECT m.file AS a, g.file AS b, count(DISTINCT m.commit_hash) AS shared
            FROM mine m JOIN sizes s ON s.commit_hash = m.commit_hash AND s.n <= ${sweep}
            JOIN git_commits g ON g.commit_hash = m.commit_hash AND g.file <> m.file
            GROUP BY 1, 2 HAVING count(DISTINCT m.commit_hash) >= 2`) : Promise.resolve([]),
    ])
    const summary = new Map(contents.map(c => [String(c.file), firstComment(String(c.head ?? ""))]))
    const exports = new Map<string, string[]>()
    for (const u of units) exports.set(String(u.file), [...(exports.get(String(u.file)) ?? []), String(u.name)])
    const usedBy = new Map<string, Set<string>>(), uses = new Map<string, Set<string>>()
    for (const e of edges) {
        const a = String(e.a), b = String(e.b)
        if (!uses.has(a)) uses.set(a, new Set()); uses.get(a)!.add(b)
        if (!usedBy.has(b)) usedBy.set(b, new Set()); usedBy.get(b)!.add(a)
    }
    const partners = new Map<string, Array<{ file: string; shared: number }>>()
    // Co-change partners that are code: a design doc changing alongside says little about structure.
    for (const c of co) {
        const b = String(c.b)
        if (!CODE_EXTENSIONS.has(extensionOf(b))) continue
        partners.set(String(c.a), [...(partners.get(String(c.a)) ?? []), { file: b, shared: Number(c.shared) || 0 }])
    }
    return rows.map(r => {
        const p = String(r.name)
        return {
            path: p,
            lines: Number(r.lines) || 0,
            role: String(r.role ?? "production"),
            commits: Number(r.commits) || 0,
            health: r.health === null || r.health === undefined || Number(r.health) === 0 ? null : Number(r.health),
            summary: summary.get(p) ?? "",
            exports: exports.get(p) ?? [],
            // Tests that use a file say it is tested, not where it belongs.
            usedBy: [...(usedBy.get(p) ?? [])].filter(f => !isTestPath(f)).sort(),
            testedBy: [...(usedBy.get(p) ?? [])].filter(f => isTestPath(f)).sort(),
            uses: [...(uses.get(p) ?? [])].sort(),
            changesWith: (partners.get(p) ?? []).sort((a, b) => b.shared - a.shared || a.file.localeCompare(b.file)).slice(0, 8),
        }
    }).sort((a, b) => a.path.localeCompare(b.path))
}
